name: Minimal CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

jobs:
  lint:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: rustup show active-toolchain
      - run: rustup component add rustfmt clippy
      - uses: Swatinem/rust-cache@v2

      - run: cargo fmt --all -- --check
      - run: cargo clippy --workspace --all-features --all-targets -- -D clippy::all

  doc:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: rustup show active-toolchain
      - uses: Swatinem/rust-cache@v2

      - run: cargo test --workspace --all-features --doc
      - run: cargo doc --workspace --all-features --document-private-items --no-deps

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - run: rustup show active-toolchain
      - uses: Swatinem/rust-cache@v2

      - run: cargo test --workspace --all-features --all-targets
